version: "3.9"

services:
  nextjs-app:
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229" # Puerto para debugging
    command: npm run dev
